#Requires -Version 5.1
<#
.SYNOPSIS
  Cognitive Stress — Windows desktop widget. Thin WebView2 host only.

.DESCRIPTION
  The card itself — TODAY's full daily view (composite, sparkline, off-hours
  nag, per-hour concurrency chart, axis tiles) — is rendered by the CLI:
  `aicogstress --emit-html-card` prints one self-contained HTML fragment
  (inline CSS + SVG, no scripts), built by ai_code_cognitive_stress/output/widget_card.py.
  That module is the SINGLE renderer shared with the KDE Plasma widget and
  the macOS Übersicht widget, so the surfaces can't drift. This file just
  runs the CLI on a timer and shows its output in a WebView2 control.

  Private: shells out to a local CLI and renders its stdout from memory
  (NavigateToString, no URL loaded). The card contains no scripts and no
  external references; the only JavaScript run in the view is our own
  one-liner that measures the card's height.

  No network calls at runtime. The WebView2 DLLs in lib/ are populated by
  fetch-webview2.ps1 (a one-time maintainer/install-time action). The host
  only navigates via NavigateToString (NavigationStarting cancels anything
  else). The card is fully self-contained (inline CSS + SVG), so this is
  purely defensive.

.PARAMETER RefreshSeconds
  How often to re-run aicogstress (default: 60, minimum: 10).
  Override: set the AICOGSTRESS_REFRESH_SECONDS environment variable.

.PARAMETER Command
  Full path or name of the aicogstress CLI (default: "aicogstress").
  A GUI process may not inherit your shell PATH — if the card stays blank,
  pass the absolute path here or set AICOGSTRESS_CMD.
  Find it with: (Get-Command aicogstress).Source

.PARAMETER SelfTest
  Headless CI mode: load -CardFile <path>, wait for a height measurement,
  print "SELFTEST OK h=<px> w=<px>", and exit 0. Exits 1 on timeout/failure.
  Does not show the tray icon or enter the normal run loop.

.PARAMETER CardFile
  Path to a pre-rendered card HTML file (used with -SelfTest; the demo card
  generated by: python scripts/generate_demo_report.py --dayview-card card.html).

.EXAMPLE
  # Normal launch (add to your Startup folder via install.py --windows):
  powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden `
    -File "%LOCALAPPDATA%\Programs\aicogstress\widget\cognitive-stress.ps1"

.EXAMPLE
  # CI self-test:
  powershell -ExecutionPolicy Bypass -File cognitive-stress.ps1 `
    -SelfTest -CardFile card.html

.NOTES
  Install: python install.py --windows (from the repo root).
  Source:  desktop/windows/cognitive-stress.ps1
  DLLs:   desktop/windows/fetch-webview2.ps1 (populates lib/).
#>

[CmdletBinding()]
param(
    [int]    $RefreshSeconds = 0,         # 0 = read env / use default 60
    [string] $Command        = "",         # "" = read env / use "aicogstress"
    [switch] $SelfTest,
    [string] $CardFile       = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# 0. Resolve parameters from env overrides
# ---------------------------------------------------------------------------

if ($RefreshSeconds -le 0) {
    $envSec = [int]($env:AICOGSTRESS_REFRESH_SECONDS)
    $RefreshSeconds = if ($envSec -gt 0) { $envSec } else { 60 }
}
$RefreshSeconds = [Math]::Max(10, $RefreshSeconds)

if ($Command -eq "") {
    $Command = if ($env:AICOGSTRESS_CMD) { $env:AICOGSTRESS_CMD } else { "aicogstress" }
}

# ---------------------------------------------------------------------------
# 1. Load vendored WebView2 + WinForms DLLs
#    All three must exist in lib/ (populated by fetch-webview2.ps1).
# ---------------------------------------------------------------------------

# Join-Path takes only two components on Windows PowerShell 5.1 (the 3+ arg
# form is PowerShell 6+), so nest the calls.
$libDir = Join-Path (Join-Path $PSScriptRoot "lib") "net45"

# The managed Core.dll P/Invokes into the native WebView2Loader.dll, which is
# resolved by the standard DLL search order — and that does NOT include this
# script's directory (the process dir is wherever powershell.exe lives,
# i.e. System32). fetch-webview2.ps1 vendors the loader under
# lib/runtimes/<rid>/native; prepend that dir to PATH so the loader is found.
# (If it's absent, the Evergreen Runtime supplies one — this is belt-and-braces.)
$rid = if ([Environment]::Is64BitProcess) {
    if ([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture -eq 'Arm64') { "win-arm64" } else { "win-x64" }
} else { "win-x86" }
$nativeDir = Join-Path (Join-Path (Join-Path (Join-Path $PSScriptRoot "lib") "runtimes") $rid) "native"
if (Test-Path (Join-Path $nativeDir "WebView2Loader.dll")) {
    $env:PATH = "$nativeDir;$env:PATH"
}

$requiredDlls = @(
    "Microsoft.Web.WebView2.Core.dll",
    "Microsoft.Web.WebView2.WinForms.dll"
)

foreach ($dll in $requiredDlls) {
    $dllPath = Join-Path $libDir $dll
    if (-not (Test-Path $dllPath)) {
        $msg = @"
ERROR: Missing WebView2 managed assembly: $dllPath

Run the fetch script to download the vendored DLLs:
  powershell -ExecutionPolicy Bypass -File "$PSScriptRoot\fetch-webview2.ps1"

Or install via install.py (which calls the fetch script automatically):
  python install.py --windows
"@
        [System.Console]::Error.WriteLine($msg)
        exit 1
    }
    Add-Type -Path $dllPath
}

# WinForms is part of the .NET Framework on Windows — no separate DLL needed.
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# ---------------------------------------------------------------------------
# 2. DPI awareness — Per-Monitor-V2 so the frameless window stays sharp on
#    HiDPI / multi-monitor setups. Best-effort: we call the modern API first
#    (Windows 10 1607+) and fall back to the older SetProcessDPIAware if
#    unavailable. Degrade silently — the widget still works, just not DPI-scaled.
# ---------------------------------------------------------------------------

$dpiCode = @'
using System;
using System.Runtime.InteropServices;

public static class DpiHelper {
    [DllImport("user32.dll")]
    private static extern bool SetProcessDPIAware();

    [DllImport("user32.dll", SetLastError = true)]
    private static extern bool SetProcessDpiAwarenessContext(IntPtr value);

    // DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 = -4
    public static void SetAware() {
        try {
            // Windows 10 1607+ Per-Monitor-V2
            SetProcessDpiAwarenessContext(new IntPtr(-4));
        } catch {
            try {
                SetProcessDPIAware();
            } catch { /* not critical */ }
        }
    }
}
'@
try {
    Add-Type -TypeDefinition $dpiCode -Language CSharp
    [DpiHelper]::SetAware()
} catch {
    # DPI awareness is best-effort; don't abort the widget over it.
}

# ---------------------------------------------------------------------------
# 3. P/Invoke signatures for drag-to-move and window messaging
# ---------------------------------------------------------------------------

$pinvokeCode = @'
using System;
using System.Runtime.InteropServices;

public static class Win32 {
    [DllImport("user32.dll")]
    public static extern bool ReleaseCapture();

    [DllImport("user32.dll")]
    public static extern IntPtr SendMessage(IntPtr hWnd, int Msg, IntPtr wParam, IntPtr lParam);

    [DllImport("user32.dll", SetLastError = true)]
    public static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint uFlags);

    public const int WM_NCLBUTTONDOWN = 0xA1;
    public const int HTCAPTION        = 0x2;

    public static readonly IntPtr HWND_BOTTOM = new IntPtr(1);
    public const uint SWP_NOMOVE     = 0x0002;
    public const uint SWP_NOSIZE     = 0x0001;
    public const uint SWP_NOACTIVATE = 0x0010;
}
'@
Add-Type -TypeDefinition $pinvokeCode -Language CSharp

# ---------------------------------------------------------------------------
# 4. Constants
# ---------------------------------------------------------------------------

# Card background (outer/root gradient stop — matches the card's CSS so the
# frameless window corners blend with the card on any wallpaper):
#   background: linear-gradient(178deg, rgb(34,36,32), rgb(22,24,21))
# We use the darker end (22,24,21) as the form background; it's the dominant
# colour once the card fills the window.
$cardBg = [System.Drawing.Color]::FromArgb(22, 24, 21)

$CARD_WIDTH   = 384   # px — fixed card width from widget_card.py (CARD_WIDTH = 384)
$CARD_HEIGHT_FALLBACK = 520  # initial height while the real one is measured

$posFile     = Join-Path (Join-Path $env:LOCALAPPDATA "aicogstress") "widget-pos.json"
$wv2DataDir  = Join-Path (Join-Path $env:LOCALAPPDATA "aicogstress") "webview2"

# HTML wrapper — matches the KDE host exactly (strips the card's drop-shadow
# so the borderless window corners don't show a clipped shadow stub):
$HTML_WRAPPER_HEAD = "<!doctype html><html><head><meta charset='utf-8'>" +
    "<style>.cogstress{box-shadow:none !important;}</style>" +
    "</head><body style='margin:0;background:rgb(34,36,32)'>"
$HTML_WRAPPER_TAIL = "</body></html>"

# Error chip style — matches the Übersicht errorStyle palette:
#   color: "#d98c80", background: "rgb(24,26,23)", border: "1px solid rgba(176,74,58,.26)"
$ERROR_HTML = $HTML_WRAPPER_HEAD +
    "<div style='width:384px;padding:14px 18px;border-radius:16px;box-sizing:border-box;" +
    "font:600 10.5px/1.5 -apple-system,Helvetica,sans-serif;" +
    "color:#d98c80;background:rgb(24,26,23);" +
    "border:1px solid rgba(176,74,58,.26)'>{0}</div>" +
    $HTML_WRAPPER_TAIL

$SELFTEST_DEADLINE_SEC = 30

# WebView2's first init (Evergreen runtime warmup + fresh user-data dir) can be
# slow on a cold machine — most visibly on CI Windows runners, where 30 s was
# occasionally too tight and the self-test flaked. Allow generous headroom,
# overridable via env so CI can tune it without a code change.
$WV2_INIT_TIMEOUT_SEC = 90
if ($env:AICOGSTRESS_WV2_INIT_TIMEOUT_SEC) {
    $parsed = 0
    if ([int]::TryParse($env:AICOGSTRESS_WV2_INIT_TIMEOUT_SEC, [ref] $parsed) -and $parsed -gt 0) {
        $WV2_INIT_TIMEOUT_SEC = $parsed
    }
}

# ---------------------------------------------------------------------------
# 5. Position persistence helpers
# ---------------------------------------------------------------------------

function Read-WidgetPos {
    try {
        if (Test-Path $posFile) {
            $j = Get-Content $posFile -Raw | ConvertFrom-Json
            return [System.Drawing.Point]::new([int]$j.X, [int]$j.Y)
        }
    } catch { }
    return $null
}

function Save-WidgetPos([System.Windows.Forms.Form] $form) {
    try {
        $dir = Split-Path $posFile
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        @{ X = $form.Left; Y = $form.Top } | ConvertTo-Json | Set-Content $posFile -Encoding UTF8
    } catch { }
}

function Clamp-ToScreen([System.Drawing.Point] $pt, [int] $w, [int] $h) {
    # Keep at least 50px visible on the primary screen.
    $screens = [System.Windows.Forms.Screen]::AllScreens
    foreach ($scr in $screens) {
        $b = $scr.WorkingArea
        if ($pt.X -ge ($b.Right - 50) -or $pt.Y -ge ($b.Bottom - 50) `
            -or ($pt.X + $w) -le ($b.Left + 50) -or ($pt.Y + $h) -le ($b.Top + 50)) {
            continue
        }
        # On this screen: clamp so the title-bar area is reachable.
        $x = [Math]::Max($b.Left - $w + 50, [Math]::Min($pt.X, $b.Right - 50))
        $y = [Math]::Max($b.Top,             [Math]::Min($pt.Y, $b.Bottom - 50))
        return [System.Drawing.Point]::new($x, $y)
    }
    # Not on any screen — reset to primary top-right corner.
    $pa = [System.Windows.Forms.Screen]::PrimaryScreen.WorkingArea
    return [System.Drawing.Point]::new($pa.Right - $w - 36, 36)
}

# ---------------------------------------------------------------------------
# 6. Form region helper — clips the window to a rounded rectangle so the
#    corners outside the card's border-radius are transparent rather than
#    showing the form's background colour.  The card's outer border-radius is
#    24 px; we scale by $script:dpiScale so the clip stays sharp on HiDPI.
#    Called once on startup and re-applied on every SizeChanged event.
# ---------------------------------------------------------------------------

function Set-FormRegion([System.Windows.Forms.Form] $f) {
    $radius = [int](24 * $script:dpiScale)
    $w = $f.Width
    $h = $f.Height
    if ($w -lt $radius * 2 -or $h -lt $radius * 2) { return }
    $path = [System.Drawing.Drawing2D.GraphicsPath]::new()
    $path.AddArc(0,              0,              $radius * 2, $radius * 2, 180, 90)
    $path.AddArc($w - $radius*2, 0,              $radius * 2, $radius * 2, 270, 90)
    $path.AddArc($w - $radius*2, $h - $radius*2, $radius * 2, $radius * 2,   0, 90)
    $path.AddArc(0,              $h - $radius*2, $radius * 2, $radius * 2,  90, 90)
    $path.CloseAllFigures()
    $old = $f.Region
    $f.Region = [System.Drawing.Region]::new($path)
    if ($null -ne $old) { $old.Dispose() }
    $path.Dispose()
}

# ---------------------------------------------------------------------------
# 7. CLI invocation helper
# ---------------------------------------------------------------------------

function Invoke-AicogstressCard {
    <#
    .SYNOPSIS Run aicogstress --emit-html-card, return [pscustomobject] with
    stdout/stderr/ExitCode. Never throws.
    #>
    try {
        $psi = [System.Diagnostics.ProcessStartInfo]::new()
        $psi.FileName               = $Command
        $psi.Arguments              = "--emit-html-card --source auto"
        $psi.UseShellExecute             = $false
        $psi.RedirectStandardOutput      = $true
        $psi.RedirectStandardError       = $true
        $psi.CreateNoWindow              = $true
        $psi.StandardOutputEncoding      = [System.Text.Encoding]::UTF8
        $psi.StandardErrorEncoding       = [System.Text.Encoding]::UTF8
        $psi.EnvironmentVariables["PYTHONUTF8"] = "1"

        $proc = [System.Diagnostics.Process]::Start($psi)
        $stdout = $proc.StandardOutput.ReadToEnd()
        $stderr = $proc.StandardError.ReadToEnd()
        $proc.WaitForExit()
        return [pscustomobject]@{
            Stdout   = $stdout.Trim()
            Stderr   = $stderr.Trim()
            ExitCode = $proc.ExitCode
        }
    } catch {
        return [pscustomobject]@{
            Stdout   = ""
            Stderr   = "Failed to start '$Command': $_"
            ExitCode = -1
        }
    }
}

# ---------------------------------------------------------------------------
# 7. Build the card HTML to inject, or the error chip HTML on failure.
# ---------------------------------------------------------------------------

function Get-CardHtml {
    $r = Invoke-AicogstressCard
    if ($r.ExitCode -eq 0 -and $r.Stdout -match 'class="cogstress"') {
        return $HTML_WRAPPER_HEAD + $r.Stdout + $HTML_WRAPPER_TAIL
    }
    $msg = if ($r.Stderr) { $r.Stderr } elseif ($r.ExitCode -ne 0) {
        "'$Command' failed (exit $($r.ExitCode)). Is aicogstress on PATH? Set -Command or AICOGSTRESS_CMD."
    } else {
        "Unexpected output from '$Command' — run it in a terminal to check."
    }
    # Escape HTML entities in the error message.
    $safe = $msg -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;'
    return $ERROR_HTML.Replace('{0}', $safe)
}

# ---------------------------------------------------------------------------
# 8.  WebView2 async initialisation helper — pump the WinForms message loop
#     until CoreWebView2InitializationCompleted fires (or we give up).
# ---------------------------------------------------------------------------

function Wait-WebView2Init([Microsoft.Web.WebView2.WinForms.WebView2] $wv, [int] $TimeoutSec = $script:WV2_INIT_TIMEOUT_SEC) {
    # The completed event fires on the UI thread during DoEvents(). The handler
    # and this loop MUST share state: use script scope on both sides (a
    # function-local $done here would never see the handler's write). Distinct
    # names so we never clobber the built-in automatic $error.
    $script:wv2InitDone = $false
    $script:wv2InitErr  = $null
    $handler = {
        param($s, $e)
        if (-not $e.IsSuccess) { $script:wv2InitErr = $e.InitializationException }
        $script:wv2InitDone = $true
    }
    $wv.add_CoreWebView2InitializationCompleted([System.EventHandler[Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs]] $handler)

    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSec)
    while (-not $script:wv2InitDone -and [DateTime]::UtcNow -lt $deadline) {
        [System.Windows.Forms.Application]::DoEvents()
        Start-Sleep -Milliseconds 50
    }
    $wv.remove_CoreWebView2InitializationCompleted([System.EventHandler[Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs]] $handler)

    if ($script:wv2InitErr) { throw "WebView2 init failed: $($script:wv2InitErr)" }
    if (-not $script:wv2InitDone) { throw "WebView2 init timed out after $TimeoutSec s" }
}

# ---------------------------------------------------------------------------
# 9.  SELF-TEST mode (CI / headless)
#     Load a pre-rendered card file, wait for the height bridge, report, exit.
# ---------------------------------------------------------------------------

if ($SelfTest) {
    if (-not $CardFile -or -not (Test-Path $CardFile)) {
        [System.Console]::Error.WriteLine("SELFTEST: -CardFile not found: '$CardFile'")
        exit 1
    }

    $cardHtmlRaw = Get-Content $CardFile -Raw -Encoding UTF8
    if ($cardHtmlRaw -notmatch 'class="cogstress"') {
        [System.Console]::Error.WriteLine("SELFTEST: CardFile does not contain class=`"cogstress`"")
        exit 1
    }
    $cardHtml = $HTML_WRAPPER_HEAD + $cardHtmlRaw + $HTML_WRAPPER_TAIL

    $form = [System.Windows.Forms.Form]::new()
    $form.Width           = $CARD_WIDTH
    $form.Height          = $CARD_HEIGHT_FALLBACK
    $form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::None
    $form.ShowInTaskbar   = $false
    $form.BackColor       = $cardBg
    # Off-screen (NOT minimized): a minimized host can make WebView2 suspend
    # navigation/rendering, so the height bridge may never fire. An off-screen
    # normal window stays "visible" to WebView2 — JS runs, title bridge fires.
    $form.StartPosition   = [System.Windows.Forms.FormStartPosition]::Manual
    $form.Location        = [System.Drawing.Point]::new(-32000, -32000)

    $form.Show()

    # WebView2 first-init is the flaky step on cold CI runners. Retry once on a
    # fresh control + user-data dir — the second attempt benefits from the
    # now-warm Evergreen runtime — each attempt bounded by $WV2_INIT_TIMEOUT_SEC.
    $wv = $null
    $tmpUdd = $null
    $initErr = $null
    foreach ($attempt in 1..2) {
        $tmpUdd = Join-Path ([System.IO.Path]::GetTempPath()) "aicogstress-selftest-$([System.Guid]::NewGuid().ToString('N'))"
        New-Item -ItemType Directory -Path $tmpUdd -Force | Out-Null
        $wv = [Microsoft.Web.WebView2.WinForms.WebView2]::new()
        $wv.Dock = [System.Windows.Forms.DockStyle]::Fill
        $form.Controls.Add($wv)
        try {
            $wv2Env = [Microsoft.Web.WebView2.Core.CoreWebView2Environment]::CreateAsync($null, $tmpUdd, $null).GetAwaiter().GetResult()
            $wv.EnsureCoreWebView2Async($wv2Env) | Out-Null
            Wait-WebView2Init $wv
            $initErr = $null
            break
        } catch {
            $initErr = $_
            [System.Console]::Error.WriteLine("SELFTEST: WebView2 init attempt $attempt/2 failed: $_")
            try { $form.Controls.Remove($wv); $wv.Dispose() } catch { }
            try { Remove-Item $tmpUdd -Recurse -Force -ErrorAction SilentlyContinue } catch { }
        }
    }
    if ($initErr) {
        [System.Console]::Error.WriteLine("SELFTEST FAIL: WebView2 init error: $initErr")
        $form.Close()
        exit 1
    }

    # Disable remote features (defensive; same as normal mode).
    $wv.CoreWebView2.Settings.AreDevToolsEnabled             = $false
    $wv.CoreWebView2.Settings.AreDefaultContextMenusEnabled  = $false
    $wv.CoreWebView2.Settings.IsStatusBarEnabled             = $false
    $wv.CoreWebView2.Settings.IsBuiltInErrorPageEnabled      = $false

    # Block any navigation that isn't our injected content.
    $wv.CoreWebView2.add_NavigationStarting({
        param($s, $e)
        $uri = $e.Uri
        if ($uri -notmatch '^(about:|data:)') {
            $e.Cancel = $true
        }
    })

    $measuredH = 0
    $measuredW = 0

    # Height bridge: parse cogstress:h:<px> from document.title.
    $wv.CoreWebView2.add_DocumentTitleChanged({
        param($s, $e)
        $t = $wv.CoreWebView2.DocumentTitle
        if ($t -match '^cogstress:h:(\d+)$') {
            $script:measuredH = [int]$Matches[1]
        }
    })

    # NavigationCompleted just flips a flag — measurement happens on this UI
    # thread below.
    $script:navDone = $false
    $wv.CoreWebView2.add_NavigationCompleted({
        param($s, $e)
        $script:navDone = $true
    })

    $wv.CoreWebView2.NavigateToString($cardHtml)

    # Two height paths: the title bridge (cogstress:h:<px>, the tabbed card's
    # fast path, handled on the UI thread above) and a getBoundingClientRect
    # poll (reliable fallback for a static card). We poll ExecuteScriptAsync's
    # task from THIS UI-thread loop — reading .Result once .IsCompleted — rather
    # than a .ContinueWith continuation: a continuation runs on a threadpool
    # thread with no PowerShell runspace and would never execute.
    $measureTask = $null
    $deadline = [DateTime]::UtcNow.AddSeconds($SELFTEST_DEADLINE_SEC)
    while ([DateTime]::UtcNow -lt $deadline) {
        [System.Windows.Forms.Application]::DoEvents()
        if ($measuredH -gt 0) { break }
        if ($script:navDone -and $null -eq $measureTask) {
            $measureTask = $wv.CoreWebView2.ExecuteScriptAsync(
                "Math.ceil(document.querySelector('.cogstress')?" +
                "document.querySelector('.cogstress').getBoundingClientRect().height:0)")
        }
        if ($null -ne $measureTask -and $measureTask.IsCompleted) {
            try {
                # A number result is returned JSON-encoded (e.g. 520); strip any
                # quotes defensively and parse.
                $h = 0
                if ([int]::TryParse(($measureTask.Result -replace '"', ''), [ref] $h) -and $h -gt 0) {
                    $script:measuredH = $h
                }
            } catch { }
            # Result arrived but layout not ready yet (0) — re-measure next loop.
            if ($measuredH -le 0) { $measureTask = $null }
        }
        Start-Sleep -Milliseconds 100
    }

    $form.Close()
    try { Remove-Item $tmpUdd -Recurse -Force -ErrorAction SilentlyContinue } catch { }

    if ($measuredH -gt 0) {
        $w = if ($measuredW -gt 0) { $measuredW } else { $CARD_WIDTH }
        Write-Host "SELFTEST OK h=$measuredH w=$w"
        exit 0
    } else {
        [System.Console]::Error.WriteLine("SELFTEST FAIL: height not measured within ${SELFTEST_DEADLINE_SEC}s")
        exit 1
    }
}

# ---------------------------------------------------------------------------
# 10. NORMAL MODE — build the WinForms UI
# ---------------------------------------------------------------------------

# DPI scale factor — read once at startup; assumes zoom is fixed per screen.
# WebView2 is always per-monitor DPI aware, so CSS pixels scale with DPI.
# WinForms may not be (depends on PowerShell's process DPI awareness), so we
# scale the form dimensions explicitly to match WebView2's physical footprint.
$script:dpiScale        = 1.0
$script:scaledCardWidth = $CARD_WIDTH
$script:dragBarHeight   = 8
try {
    $g = [System.Drawing.Graphics]::FromHwnd([IntPtr]::Zero)
    $script:dpiScale        = [double]$g.DpiX / 96.0
    $script:scaledCardWidth = [int]($CARD_WIDTH * $script:dpiScale)
    $script:dragBarHeight   = [Math]::Max(6, [int](8 * $script:dpiScale))
    $g.Dispose()
} catch { }

$form = [System.Windows.Forms.Form]::new()
$form.Text            = "aicogstress"
$form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::None
$form.TopMost         = $false
$form.ShowInTaskbar   = $false
$form.StartPosition   = [System.Windows.Forms.FormStartPosition]::Manual
$form.BackColor       = $cardBg
$form.Width           = $script:scaledCardWidth
$form.Height          = [int]($CARD_HEIGHT_FALLBACK * $script:dpiScale)

# Re-apply the rounded clip any time the form is resized (initial size,
# height-bridge update, or manual resize).
$form.add_SizeChanged({ Set-FormRegion $form })
Set-FormRegion $form

# Restore saved position (clamped to visible screen).
$savedPos = Read-WidgetPos
if ($savedPos) {
    $clamped = Clamp-ToScreen $savedPos $script:scaledCardWidth $form.Height
    $form.Location = $clamped
} else {
    # Default: top-right corner of primary screen with a 36px margin.
    $pa = [System.Windows.Forms.Screen]::PrimaryScreen.WorkingArea
    $form.Location = [System.Drawing.Point]::new($pa.Right - $script:scaledCardWidth - 36, 36)
}

# ---------------------------------------------------------------------------
# 11. WebView2 control
# ---------------------------------------------------------------------------

$wv = [Microsoft.Web.WebView2.WinForms.WebView2]::new()
$wv.Dock = [System.Windows.Forms.DockStyle]::Fill
$form.Controls.Add($wv)

# Drag handle — a thin panel docked above the WebView2 content. Adding it
# after $wv gives it a higher Controls index, so WinForms processes its
# Dock=Top first and $wv (Dock=Fill) takes the space below.
$dragBar = [System.Windows.Forms.Panel]::new()
$dragBar.Dock      = [System.Windows.Forms.DockStyle]::Top
$dragBar.Height    = $script:dragBarHeight
$dragBar.BackColor = [System.Drawing.Color]::FromArgb(34, 36, 32)
$dragBar.Cursor    = [System.Windows.Forms.Cursors]::SizeAll
$dragBar.add_MouseDown({
    param($s, $e)
    if ($e.Button -eq [System.Windows.Forms.MouseButtons]::Left) {
        [Win32]::ReleaseCapture() | Out-Null
        [Win32]::SendMessage($form.Handle, [Win32]::WM_NCLBUTTONDOWN,
            [IntPtr]::new([Win32]::HTCAPTION), [IntPtr]::Zero) | Out-Null
    }
})
$dragBar.add_Paint({
    param($s, $e)
    $brush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(60, 65, 57))
    $cx = [int]($dragBar.Width / 2)
    $cy = [int]($dragBar.Height / 2)
    foreach ($i in -1, 0, 1) {
        $e.Graphics.FillEllipse($brush, $cx + $i * 7 - 2, $cy - 2, 4, 4)
    }
    $brush.Dispose()
})
$form.Controls.Add($dragBar)

# Make the form visible before EnsureCoreWebView2Async, so WebView2 has a
# valid HWND to attach to (required for the WinForms control).
$form.Show()

# Send to bottom of Z-order so the widget sits behind all normal windows.
[Win32]::SetWindowPos($form.Handle, [Win32]::HWND_BOTTOM, 0, 0, 0, 0,
    [Win32]::SWP_NOMOVE -bor [Win32]::SWP_NOSIZE -bor [Win32]::SWP_NOACTIVATE) | Out-Null
# Re-assert whenever Windows activates the form (e.g. accidental click).
$form.add_Activated({
    [Win32]::SetWindowPos($form.Handle, [Win32]::HWND_BOTTOM, 0, 0, 0, 0,
        [Win32]::SWP_NOMOVE -bor [Win32]::SWP_NOSIZE -bor [Win32]::SWP_NOACTIVATE) | Out-Null
})

# Async init: pump the message loop until initialisation completes.
$wv2Env = $null
try {
    [System.IO.Directory]::CreateDirectory($wv2DataDir) | Out-Null
    $wv2Env = [Microsoft.Web.WebView2.Core.CoreWebView2Environment]::CreateAsync($null, $wv2DataDir, $null).GetAwaiter().GetResult()
    $wv.EnsureCoreWebView2Async($wv2Env) | Out-Null
    Wait-WebView2Init $wv
} catch {
    [System.Console]::Error.WriteLine("ERROR: WebView2 init failed: $_")
    [System.Console]::Error.WriteLine("Is the WebView2 Runtime installed? See: https://developer.microsoft.com/en-us/microsoft-edge/webview2/")
    $form.Close()
    exit 1
}

# ---------------------------------------------------------------------------
# 12. Harden the WebView2 settings after init
# ---------------------------------------------------------------------------

$wv.CoreWebView2.Settings.AreDevToolsEnabled              = $false
$wv.CoreWebView2.Settings.AreDefaultContextMenusEnabled   = $false
$wv.CoreWebView2.Settings.IsStatusBarEnabled              = $false
$wv.CoreWebView2.Settings.IsBuiltInErrorPageEnabled       = $false
# Disable remote content (belt-and-suspenders; the card is purely local).
try {
    # Available in WebView2 SDK >= 1.0.1823; ignore if the property doesn't exist.
    $wv.CoreWebView2.Settings.IsReputationCheckingRequired = $false
} catch { }

# Cancel any navigation that isn't our injected content. The card is injected
# via NavigateToString, which shows as an "about:blank" or "data:" navigation.
# Any real URL (http/https) would mean something unexpected — block it.
$wv.CoreWebView2.add_NavigationStarting({
    param($sender, $e)
    $uri = $e.Uri
    if ($uri -notmatch '^(about:|data:)') {
        $e.Cancel = $true
    }
})

# ---------------------------------------------------------------------------
# 13. Height bridge: document.title = "cogstress:h:<px>" → resize the form.
#     Also fire getBoundingClientRect on NavigationCompleted as the initial
#     fallback measure (for a static non-tabbed card, which sets no title).
# ---------------------------------------------------------------------------

$wv.CoreWebView2.add_DocumentTitleChanged({
    param($s, $e)
    $t = $wv.CoreWebView2.DocumentTitle
    # Grade bridge: 'cogstress:rate:<day>:<grade>[:<nonce>]' — invoke the CLI
    # with --rate so the sidecar is written. The nonce (if present) is stripped.
    # The host re-runs --emit-html-card on its refresh timer; the next refresh
    # reads the sidecar and the grader collapses to the confirmation state.
    if ($t -match '^cogstress:rate:(\d{4}-\d{2}-\d{2}):([0-2])(?::\d+)?$') {
        $rateDay   = $Matches[1]
        $rateGrade = $Matches[2]
        try {
            $psiRate = [System.Diagnostics.ProcessStartInfo]::new()
            $psiRate.FileName               = $Command
            $psiRate.Arguments              = "--rate $rateDay`:$rateGrade"
            $psiRate.UseShellExecute        = $false
            $psiRate.RedirectStandardOutput = $true
            $psiRate.RedirectStandardError  = $true
            $psiRate.CreateNoWindow         = $true
            $psiRate.StandardOutputEncoding = [System.Text.Encoding]::UTF8
            $psiRate.StandardErrorEncoding  = [System.Text.Encoding]::UTF8
            $psiRate.EnvironmentVariables["PYTHONUTF8"] = "1"
            $procRate = [System.Diagnostics.Process]::Start($psiRate)
            $procRate.WaitForExit() | Out-Null
        } catch { }
        return
    }
    # Compact toggle: 'cogstress:compact:<0|1>[:<nonce>]' — persist via
    # `aicogstress --set-compact <true|false>`, then re-render immediately so
    # the card resizes without waiting for the refresh timer.
    if ($t -match '^cogstress:compact:([01])(?::\d+)?$') {
        $compactVal = if ($Matches[1] -eq '1') { 'true' } else { 'false' }
        try {
            $psiC = [System.Diagnostics.ProcessStartInfo]::new()
            $psiC.FileName               = $Command
            $psiC.Arguments              = "--set-compact $compactVal"
            $psiC.UseShellExecute        = $false
            $psiC.RedirectStandardOutput = $true
            $psiC.RedirectStandardError  = $true
            $psiC.CreateNoWindow         = $true
            $psiC.StandardOutputEncoding = [System.Text.Encoding]::UTF8
            $psiC.StandardErrorEncoding  = [System.Text.Encoding]::UTF8
            $psiC.EnvironmentVariables["PYTHONUTF8"] = "1"
            $procC = [System.Diagnostics.Process]::Start($psiC)
            $procC.WaitForExit() | Out-Null
        } catch { }
        $html = Get-CardHtml
        $wv.CoreWebView2.NavigateToString($html)
        return
    }
    # View tab persist: 'cogstress:view:<key>[:<nonce>]' — persist only via
    # `aicogstress --set-view <key>`. No NavigateToString re-render: the card's
    # own script already switched the visible tab client-side; re-rendering here
    # would flicker/snap back to the current view. The next timer refresh will
    # open to the persisted tab.
    if ($t -match '^cogstress:view:(today|week|month|year)(?::\d+)?$') {
        $viewKey = $Matches[1]
        try {
            $psiV = [System.Diagnostics.ProcessStartInfo]::new()
            $psiV.FileName               = $Command
            $psiV.Arguments              = "--set-view $viewKey"
            $psiV.UseShellExecute        = $false
            $psiV.RedirectStandardOutput = $true
            $psiV.RedirectStandardError  = $true
            $psiV.CreateNoWindow         = $true
            $psiV.StandardOutputEncoding = [System.Text.Encoding]::UTF8
            $psiV.StandardErrorEncoding  = [System.Text.Encoding]::UTF8
            $psiV.EnvironmentVariables["PYTHONUTF8"] = "1"
            $procV = [System.Diagnostics.Process]::Start($psiV)
            $procV.WaitForExit() | Out-Null
        } catch { }
        return
    }
    # Height bridge: 'cogstress:h:<px>'
    if ($t -match '^cogstress:h:(\d+)$') {
        $h = [int]$Matches[1]
        if ($h -gt 0) {
            $form.ClientSize = [System.Drawing.Size]::new($script:scaledCardWidth, [int]($h * $script:dpiScale) + $script:dragBarHeight)
            Save-WidgetPos $form
        }
    }
})

# Static-card fallback height. The tabbed card resizes via the title bridge
# above; a static card sets no title, so measure it with getBoundingClientRect
# after navigation. We can't read the ExecuteScriptAsync result in a
# .ContinueWith continuation — that runs on a threadpool thread with no
# PowerShell runspace and would silently never execute. Instead, kick the
# script off on NavigationCompleted and poll its task from a short
# WinForms.Timer, whose Tick fires on the UI thread (via the message loop, so
# it has a runspace — the same mechanism as the refresh timer below).
$script:measureTask = $null
$measurePoll = [System.Windows.Forms.Timer]::new()
$measurePoll.Interval = 150
$measurePoll.add_Tick({
    if ($null -eq $script:measureTask -or -not $script:measureTask.IsCompleted) { return }
    $measurePoll.Stop()
    try {
        $h = 0
        if ([int]::TryParse(($script:measureTask.Result -replace '"', ''), [ref] $h) -and $h -gt 0) {
            $form.ClientSize = [System.Drawing.Size]::new($script:scaledCardWidth, [int]($h * $script:dpiScale) + $script:dragBarHeight)
            Save-WidgetPos $form
        }
    } catch { }
    $script:measureTask = $null
})

$wv.CoreWebView2.add_NavigationCompleted({
    param($s, $e)
    $script:measureTask = $wv.CoreWebView2.ExecuteScriptAsync(
        "Math.ceil(document.querySelector('.cogstress')?" +
        "document.querySelector('.cogstress').getBoundingClientRect().height:0)")
    $measurePoll.Start()
})

# ---------------------------------------------------------------------------
# 14. Drag-to-move: handled by $dragBar (the thin panel above the WebView2).
#     MouseDown on the form is kept as a fallback for any remaining border px.
# ---------------------------------------------------------------------------

$form.add_MouseDown({
    param($s, $e)
    if ($e.Button -eq [System.Windows.Forms.MouseButtons]::Left) {
        [Win32]::ReleaseCapture() | Out-Null
        [Win32]::SendMessage($form.Handle, [Win32]::WM_NCLBUTTONDOWN,
            [IntPtr]::new([Win32]::HTCAPTION), [IntPtr]::Zero) | Out-Null
    }
})

# Save position whenever the window stops moving.
$form.add_Move({ Save-WidgetPos $form })
$form.add_FormClosing({ Save-WidgetPos $form })

# ---------------------------------------------------------------------------
# 15. Tray icon — the only way to close a no-taskbar window. Required.
# ---------------------------------------------------------------------------

# Use a simple colored icon built from a drawing (no .ico file dependency).
$iconBitmap = [System.Drawing.Bitmap]::new(16, 16)
$g = [System.Drawing.Graphics]::FromImage($iconBitmap)
$g.Clear([System.Drawing.Color]::FromArgb(22, 24, 21))
$g.FillEllipse([System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(108, 154, 139)), 2, 2, 12, 12)
$g.Dispose()
$trayIcon = [System.Windows.Forms.NotifyIcon]::new()
$trayIcon.Icon    = [System.Drawing.Icon]::FromHandle($iconBitmap.GetHicon())
$trayIcon.Text    = "Cognitive Stress"
$trayIcon.Visible = $true

$ctxMenu   = [System.Windows.Forms.ContextMenuStrip]::new()
$miRefresh = [System.Windows.Forms.ToolStripMenuItem]::new("Refresh now")
$miQuit    = [System.Windows.Forms.ToolStripMenuItem]::new("Quit")

$miRefresh.add_Click({
    $html = Get-CardHtml
    $wv.CoreWebView2.NavigateToString($html)
})
$miQuit.add_Click({
    $timer.Stop()
    $trayIcon.Visible = $false
    $trayIcon.Dispose()
    [System.Windows.Forms.Application]::Exit()
})

$ctxMenu.Items.Add($miRefresh) | Out-Null
$ctxMenu.Items.Add([System.Windows.Forms.ToolStripSeparator]::new()) | Out-Null
$ctxMenu.Items.Add($miQuit) | Out-Null
$trayIcon.ContextMenuStrip = $ctxMenu

# Double-click tray icon to refresh the card immediately.
$trayIcon.add_DoubleClick({
    $html = Get-CardHtml
    $wv.CoreWebView2.NavigateToString($html)
})

# ---------------------------------------------------------------------------
# 16. Refresh timer — run the CLI on a fixed interval, inject the result.
# ---------------------------------------------------------------------------

$timer = [System.Windows.Forms.Timer]::new()
$timer.Interval = $RefreshSeconds * 1000

$timer.add_Tick({
    $html = Get-CardHtml
    $wv.CoreWebView2.NavigateToString($html)
})

# Initial load — fire immediately before the first tick.
$initialHtml = Get-CardHtml
$wv.CoreWebView2.NavigateToString($initialHtml)

$timer.Start()

# ---------------------------------------------------------------------------
# 17. Run the WinForms message loop.
# ---------------------------------------------------------------------------

[System.Windows.Forms.Application]::Run($form)

# Cleanup on exit.
try {
    $timer.Stop()
    $timer.Dispose()
    $measurePoll.Stop()
    $measurePoll.Dispose()
    $trayIcon.Visible = $false
    $trayIcon.Dispose()
    $iconBitmap.Dispose()
} catch { }
